import { expect, test, type Page } from '@playwright/test'

async function openStudio(page: Page) {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '선택지 담기' })).toBeVisible()
}

async function startEmpty(page: Page) {
  await page.getByRole('button', { name: '새로 만들기', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '새로 만들기', exact: true }).click()
  await expect(page.locator('.item-row')).toHaveCount(0)
}

async function addItems(page: Page, labels: string[]) {
  await page.getByRole('button', { name: '여러 항목 한 번에 추가' }).click()
  await page.getByLabel('추가할 항목').fill(labels.join('\n'))
  await page.getByRole('button', { name: '선택지에 추가하기' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
}

test('responsive studio renders without overflow or browser errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openStudio(page)
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'outputs/browser/desktop-1440.png', fullPage: true, animations: 'disabled' })
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: width === 1440 ? 1100 : 844 })
    await expect(page.getByRole('button', { name: '행운 뽑기', exact: true })).toBeVisible()
    const sizes = await page.evaluate(() => ({ inner: innerWidth, document: document.documentElement.scrollWidth }))
    expect(sizes.document, `horizontal overflow at ${width}px`).toBeLessThanOrEqual(sizes.inner)
    if (width === 390) {
      // Chromium may omit offscreen backdrop-filter layers until they have painted.
      await page.locator('.editor-panel').scrollIntoViewIfNeeded()
      await page.screenshot({ path: 'outputs/browser/mobile-editor-scrolled.png', animations: 'disabled' })
      await page.screenshot({ path: 'outputs/browser/mobile-390.png', fullPage: true, animations: 'disabled' })
    }
  }
  expect(errors).toEqual([])
})

test('text editing, weight normalization, slider, deletion and persistence', async ({ page }) => {
  await openStudio(page)
  await startEmpty(page)
  await expect(page.getByRole('button', { name: '행운 뽑기', exact: true })).toBeDisabled()
  await addItems(page, ['사과', '배'])
  await page.getByRole('spinbutton', { name: '항목 1 비중 직접 입력' }).fill('30')
  await page.getByRole('spinbutton', { name: '항목 2 비중 직접 입력' }).fill('10')
  await expect(page.locator('.item-percentage')).toHaveText(['75%', '25%'])
  await page.getByRole('textbox', { name: '항목 2 이름' }).fill('포도')
  await page.getByRole('slider', { name: '항목 2 비중', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('spinbutton', { name: '항목 2 비중 직접 입력' })).toHaveValue('11')
  await page.getByRole('button', { name: '균등하게' }).click()
  await expect(page.locator('.item-percentage')).toHaveText(['50%', '50%'])
  await page.getByRole('button', { name: '항목 추가', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '항목 3 이름' })).toBeFocused()
  await expect(page.locator('.item-percentage')).toHaveText(['50%', '50%', '0%'])
  await page.getByRole('textbox', { name: '항목 3 이름' }).fill('복숭아')
  await page.getByRole('button', { name: '항목 3 삭제' }).click()
  await expect(page.locator('.item-row')).toHaveCount(2)
  await page.getByRole('button', { name: '되돌리기' }).click()
  await expect(page.locator('.item-row')).toHaveCount(3)
  await page.reload()
  await expect(page.getByRole('textbox', { name: '항목 2 이름' })).toHaveValue('포도')
  await expect(page.getByRole('textbox', { name: '항목 3 이름' })).toHaveValue('복숭아')
})

test('draw is deterministic with one eligible item; excludes, exhausts, resets and restores history', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await openStudio(page)
  await startEmpty(page)
  await addItems(page, ['당첨 항목', '제외 항목'])
  await page.getByRole('spinbutton', { name: '항목 2 비중 직접 입력' }).fill('0')
  await page.getByRole('switch', { name: '당첨된 항목 제외' }).click()
  await page.getByRole('button', { name: '행운 뽑기', exact: true }).click()
  await expect(page.locator('.result-card h3')).toHaveText('당첨 항목')
  await expect(page.locator('.history-list li')).toHaveCount(1)
  await expect(page.locator('.result-probability')).toContainText('100%')
  await expect(page.getByRole('button', { name: '새 라운드 시작하기' })).toBeEnabled()
  await expect(page.getByRole('slider', { name: '항목 1 비중', exact: true })).toBeDisabled()
  await page.screenshot({ path: 'outputs/browser/desktop-result.png', fullPage: true, animations: 'disabled' })
  await page.reload()
  await expect(page.locator('.history-list li')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '새 라운드 시작하기' })).toBeEnabled()
  await page.getByRole('button', { name: '새 라운드 시작하기' }).click()
  await expect(page.locator('.item-percentage')).toHaveText(['100%', '0%'])
  await page.getByRole('button', { name: '행운 뽑기', exact: true }).click()
  await expect(page.locator('.history-list li')).toHaveCount(2)
  await page.getByRole('button', { name: '기록 비우기' }).click()
  await expect(page.locator('.history-list li')).toHaveCount(0)
  await page.getByRole('button', { name: '되돌리기' }).click()
  await expect(page.locator('.history-list li')).toHaveCount(2)
})

test('bulk input validates empty, overlong and excess entries; dialog keyboard works', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: '여러 항목 한 번에 추가' }).click()
  await page.getByRole('button', { name: '선택지에 추가하기' }).click()
  await expect(page.getByRole('alert')).toContainText('한 줄에 하나씩')
  await page.getByLabel('추가할 항목').fill('가'.repeat(61))
  await page.getByRole('button', { name: '선택지에 추가하기' }).click()
  await expect(page.getByRole('alert')).toContainText('60자')
  await page.getByLabel('추가할 항목').fill(Array.from({ length: 26 }, (_, i) => `항목 ${i}`).join('\n'))
  await page.getByRole('button', { name: '선택지에 추가하기' }).click()
  await expect(page.getByRole('alert')).toContainText('30개')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('button', { name: '여러 항목 한 번에 추가' })).toBeFocused()
  await page.getByRole('button', { name: '이용 방법' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.locator('.history-list li')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('storage denied still permits drawing and clearly reports unavailable persistence', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Storage denied', 'SecurityError') } })
  })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await openStudio(page)
  await expect(page.locator('.save-status')).toContainText('저장할 수 없는 환경')
  await page.getByRole('button', { name: '행운 뽑기', exact: true }).click()
  await expect(page.locator('.result-card')).toBeVisible()
  await expect(page.locator('.history-list li')).toHaveCount(1)
})

test('Space activates only outside input controls and locks mutations during animation', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('textbox', { name: '항목 1 이름' }).focus()
  await page.keyboard.press('Space')
  await expect(page.locator('.history-list li')).toHaveCount(0)
  await page.locator('h1').click()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: '행운을 고르는 중…' })).toBeDisabled()
  await expect(page.getByRole('button', { name: '항목 추가', exact: true })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: '항목 1 이름' })).toBeDisabled()
  await page.keyboard.press('Space')
  await expect(page.locator('.history-list li')).toHaveCount(1)
})

test('mobile editor, named help control and long result remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await openStudio(page)
  await page.getByRole('button', { name: '이용 방법' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '좋아요, 시작할게요' }).click()
  await startEmpty(page)
  const label = '가나다라마바사아자차카타파하'.repeat(5).slice(0, 60)
  await page.getByRole('button', { name: '항목 추가', exact: true }).click()
  await page.getByRole('textbox', { name: '항목 1 이름' }).fill(label)
  await page.getByRole('spinbutton', { name: '항목 1 비중 직접 입력' }).fill('100')
  await page.getByRole('button', { name: '행운 뽑기', exact: true }).click()
  await expect(page.locator('.result-card h3')).toHaveText(label)
  await page.locator('.result-card').scrollIntoViewIfNeeded()
  const resultBounds = await page.locator('.result-card').boundingBox()
  const actionBounds = await page.locator('.draw-action').boundingBox()
  expect(resultBounds).not.toBeNull()
  expect(actionBounds).not.toBeNull()
  expect(resultBounds!.y + resultBounds!.height).toBeLessThanOrEqual(actionBounds!.y)
  const sizes = await page.evaluate(() => ({ inner: innerWidth, document: document.documentElement.scrollWidth }))
  expect(sizes.document).toBeLessThanOrEqual(sizes.inner)
  await page.screenshot({ path: 'outputs/browser/mobile-result-390.png', animations: 'disabled' })
})
